name: Python CI

on:
  push:
    branches:
      - main
  workflow_dispatch: # This allows manual triggering of workflow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build project
      run: |
        # Add your build commands here
        # For example, if your project uses Flask, you may not need a build step
        # If you have any build steps, replace the following line with your build command
        echo "No build step required"

    - name: Run tests
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        python -m unittest discover -s tests -p '*_test.py'
